name: learn_app_6
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
#  flutter:
#    sdk: flutter

#  shared_preferences_web: ^0.1.2+5
#  firebase_core_web: ^0.1.1+2
#  flutter_web_image_picker: ^0.0.2
#  firebase_auth_web: ^0.1.2
#  cloud_firestore_web: ^0.1.1
#  firebase_web:
#  google_sign_in_web:

  flutter_icons: ^1.0.0+1
  flutter_launcher_icons: ^0.7.4
  fluttertoast: ^4.0.1
  permission_handler: ^4.2.0+hotfix.3


#  syncfusion_flutter_calendar: ^18.1.45-beta


  flutter_clean_calendar: ^1.0.1
  flutter_full_pdf_viewer: ^1.0.6
  share: ^0.6.3+6
  audioplayers: ^0.15.0
  video_player: ^0.10.7
  barcode_scan: ^2.0.1
  ff_navigation_bar: ^0.1.5
  line_icons: ^0.2.0
  google_nav_bar: ^2.1.0
  bottom_personalized_dot_bar: ^1.0.2
  fancy_bottom_navigation: ^0.3.2
  firebase_storage: ^3.0.6
  intl: ^0.16.0
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^0.8.4
  photo_view: ^0.5.0
  google_maps_flutter: ^0.5.24+1
  fab_circular_menu: ^1.0.0
  flutter_speed_dial: ^1.2.5
  flutter_radio: ^0.1.7
  loading: ^1.0.2
  flutter_facebook_login: ^3.0.0
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  dio: ^3.0.6
  flutter_widget_from_html:


#  image_gallery: ^1.2.0


  agora_rtc_engine: 1.0.10
  webview_flutter: ^0.3.21
  google_fonts: ^1.0.0
  google_sign_in: ^4.4.4
  shared_preferences: ^0.5.7
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  cached_network_image: ^2.2.0
  file_picker: ^1.4.3+2
  image_picker: ^0.6.3+4
  url_launcher: ^5.4.5
  cupertino_icons: ^0.1.3

  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
   build_runner: ^1.1.2
   build_web_compilers: ^2.6.1
   pedantic: ^1.8.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon.png"

#  flutter_test:
#    sdk: flutter


#flutter:

#  uses-material-design: true
#
#  assets:
#    - assets/images/
#    - assets/data.json
#    - assets/bg_image.png
#    - assets/splash.png
